//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatagridTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameScore
    {
        public int PlayId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Moves { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> PlayScore { get; set; }
    }
}
