//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatagridTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreBoard
    {
        public string UserName { get; set; }
        public Nullable<int> BestGameScore { get; set; }
        public int Place { get; set; }
    }
}
